[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://safe-transit-api.onrender.com/:splat"
  status = 200

[[redirects]]
  from = "/deposit/*"
  to = "https://safe-transit-api.onrender.com/deposit/:splat"
  status = 200

[[redirects]]
  from = "/payment/*"
  to = "https://safe-transit-api.onrender.com/payment/:splat"
  status = 200
